### Pasos a seguir

1- Tratamiento de nulos (no hay)

2- Encoding

3-Feature engineering, scaling

4-Modelos: entrenamieto(train,test,split)

5-MÃ©tricas

In [37]:
#Imports:

import pandas as pd
import numpy as np
import seaborn as sbs
import matplotlib.pylab as plt

In [38]:
from sklearn.impute import SimpleImputer

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler

from sklearn.preprocessing import LabelEncoder

from collections import Counter
from sklearn.datasets import make_classification

from sklearn import datasets
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
import pickle
import joblib

from sklearn import linear_model
from sklearn.linear_model import ElasticNet
from sklearn.linear_model import Ridge
from sklearn.svm import SVR
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.ensemble import ExtraTreesRegressor

from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostRegressor


#from imblearn.over_sampling import SMOTE

In [39]:

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

In [40]:
df=pd.read_csv('./data/diamonds_data_train.csv', index_col=0)
df.head()

        city  price  carat  depth  table     x     y     z   cut color clarity
0  Amsterdam   3733   1.01   65.2   56.0  6.23  6.19  4.05  Fair     H     VS2
1  Amsterdam   9452   1.51   65.0   64.0  7.10  7.03  4.59  Fair     H     VS2
2     Zurich  12765   2.00   65.2   56.0  7.92  7.87  5.15  Fair     H     VS2
3     Zurich  17713   1.99   60.5   63.0  8.20  8.11  4.93  Fair     H     VS2
4  Las Vegas   2268   0.70   65.0   56.0  5.60  5.50  3.61  Fair     H     VS2

In [41]:
df.describe()
df.info()
cols = ['city','cut', 'color', 'clarity']

cat_list = []
for col in cols:
    cat = df[col].unique()
    cat_num = len(cat)
    cat_dict = {"categorical_variable":col,
                "number_of_possible_values":cat_num,
                "values":cat}
    cat_list.append(cat_dict)
    
categories = pd.DataFrame(cat_list).sort_values(by="number_of_possible_values",
                                                ascending=False).reset_index(drop=True)
categories

<class 'pandas.core.frame.DataFrame'>
Index: 40455 entries, 0 to 40454
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   city     40455 non-null  object
 1   price    40455 non-null  int64
 2   carat    40455 non-null  float64
 3   depth    40455 non-null  float64
 4   table    40455 non-null  float64
 5   x        40455 non-null  float64
 6   y        40455 non-null  float64
 7   z        40455 non-null  float64
 8   cut      40455 non-null  object
 9   color    40455 non-null  object
 10  clarity  40455 non-null  object
dtypes: float64(6), int64(1), object(4)
memory usage: 3.7+ MB

,categorical_variable,number_of_possible_values,values
0,city,13,"[Amsterdam, Zurich, Las Vegas, Paris, Tel Aviv..."
1,clarity,8,"[VS2, SI1, SI2, I1, VS1, VVS2, VVS1, IF]"
2,color,7,"[H, J, G, D, I, F, E]"
3,cut,5,"[Fair, Ideal, Very Good, Premium, Good]"

In [42]:
#<one hot encoding:

df_one_hot_encoding = pd.get_dummies(df, 
                                          columns=cols, 
                                          drop_first=True,
                                    )
df_one_hot_encoding.tail()

,price,carat,depth,table,x,y,z,city_Antwerp,city_Dubai,city_Kimberly,...,color_H,color_I,color_J,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
40450,912,0.31,57.7,55.0,4.51,4.60,2.63,False,False,False,...,False,False,False,True,False,False,False,False,False,False
40451,813,0.31,64.2,60.0,4.22,4.28,2.73,False,False,True,...,False,False,False,True,False,False,False,False,False,False
40452,612,0.28,64.6,58.0,4.09,4.12,2.65,False,False,False,...,False,False,False,True,False,False,False,False,False,False
40453,1318,0.38,59.1,58.0,4.74,4.77,2.81,False,False,False,...,False,False,False,True,False,False,False,False,False,False
40454,1052,0.31,64.2,60.0,4.28,4.22,2.73,False,False,False,...,False,False,False,True,False,False,False,False,False,False

In [43]:
'''label encoding
# Inicializar LabelEncoder
label_encoders = {}
categorical_cols = ['city', 'cut', 'color', 'clarity']

# Aplicar LabelEncoder a cada columna categÃ³rica
for col in categorical_cols:
    label_encoders[col] = LabelEncoder()
    df[col] = label_encoders[col].fit_transform(df[col])

# Mostrar los datos con columnas codificadas
print("\nDatos con columnas codificadas:")
print(df)

'''

'label encoding\n# Inicializar LabelEncoder\nlabel_encoders = {}\ncategorical_cols = [\'city\', \'cut\', \'color\', \'clarity\']\n\n# Aplicar LabelEncoder a cada columna categÃ³rica\nfor col in categorical_cols:\n    label_encoders[col] = LabelEncoder()\n    df[col] = label_encoders[col].fit_transform(df[col])\n\n# Mostrar los datos con columnas codificadas\nprint("\nDatos con columnas codificadas:")\nprint(df)\n\n'

In [44]:
df.isnull().sum() #no hay nulos
#tengo que trabajar el df y quitarle outlayers y demÃ¡s--

city       0
price      0
carat      0
depth      0
table      0
x          0
y          0
z          0
cut        0
color      0
clarity    0
dtype: int64

In [51]:
# Features and predictions one hot

X = df_one_hot_encoding.drop('price', axis=1)

y = df_one_hot_encoding['price']
print(X.shape,y.shape)

(40455, 35) (40455,)

In [46]:
''''
# Features and predictions label encoding
X = df.drop('price', axis=1)

y = df['price']
print(X.shape,y.shape)
''''''

(40455, 10) (40455,)

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"X_train: {X_train.shape}, X_test: {X_test.shape}, y_train: {y_train.shape}, y_test: {y_test.shape}")
print(f"X_train: {type(X_train)}, X_test: {type(X_test)}, y_train: {type(y_train)}, y_test: {type(y_test)}")

X_train: (32364, 35), X_test: (8091, 35), y_train: (32364,), y_test: (8091,)
X_train: <class 'pandas.core.frame.DataFrame'>, X_test: <class 'pandas.core.frame.DataFrame'>, y_train: <class 'pandas.core.series.Series'>, y_test: <class 'pandas.core.series.Series'>

In [53]:
# Model definition

#model = SVR() # GUARDADO COMO MODELO 3
#model = GradientBoostingRegressor(random_state = 42) #GUARDADO COMO MODELO 4
#model = DecisionTreeClassifier() #GUARDADO COMO MODELO 5
model=HistGradientBoostingRegressor() #GUARADO COMO MODELO 6 (a con one hot, b con label)
#model=AdaBoostRegressor() #GUARADO COMO MODELO 7
#model=ExtraTreesRegressor()#guardado como modelo 8 con one hot encoding
hyperparameters = model.get_params()

print(type(model), '\n')
print('Model hyperparameters:', hyperparameters, '\n')

<class 'sklearn.ensemble._hist_gradient_boosting.gradient_boosting.HistGradientBoostingRegressor'>

Model hyperparameters: {'categorical_features': None, 'early_stopping': 'auto', 'interaction_cst': None, 'l2_regularization': 0.0, 'learning_rate': 0.1, 'loss': 'squared_error', 'max_bins': 255, 'max_depth': None, 'max_iter': 100, 'max_leaf_nodes': 31, 'min_samples_leaf': 20, 'monotonic_cst': None, 'n_iter_no_change': 10, 'quantile': None, 'random_state': None, 'scoring': 'loss', 'tol': 1e-07, 'validation_fraction': 0.1, 'verbose': 0, 'warm_start': False}

In [75]:
'''
#customodel: np consigo mejorar cambiando hiperparÃ¡metros
model= HistGradientBoostingRegressor(
    learning_rate=0.18,
    max_iter=100,
    max_depth=2,  # Cambiado
    min_samples_leaf=20,
    max_leaf_nodes=32,
    l2_regularization=0.0,
    early_stopping='auto',  
    scoring='loss',  
    validation_fraction=0.1,
    n_iter_no_change=8,
    verbose=1,  # Cambiado
    random_state=42  # Cambiado
)
'''

In [76]:
# Model training

model.fit(X_train, y_train)

print('Model:', model, '\n')
#print('Model hyperparameters:', hyperparameters, '\n')
#print('Model coefficients:', model.coef_, '\n')

Binning 0.008 GB of training data: 0.041 s
Binning 0.001 GB of validation data: 0.001 s
Fitting gradient boosted rounds:
[1/100] 1 tree, 4 leaves, max depth = 2, train loss: 5799420.02193, val loss: 5383933.33624, in 0.003s
[2/100] 1 tree, 4 leaves, max depth = 2, train loss: 4320428.34277, val loss: 4016156.15904, in 0.003s
[3/100] 1 tree, 4 leaves, max depth = 2, train loss: 3306261.23253, val loss: 3076323.56969, in 0.004s
[4/100] 1 tree, 4 leaves, max depth = 2, train loss: 2598873.27521, val loss: 2426694.71217, in 0.004s
[5/100] 1 tree, 4 leaves, max depth = 2, train loss: 2110369.42494, val loss: 1977509.88551, in 0.003s
[6/100] 1 tree, 4 leaves, max depth = 2, train loss: 1764261.02013, val loss: 1663926.86513, in 0.002s
[7/100] 1 tree, 4 leaves, max depth = 2, train loss: 1525267.36645, val loss: 1447152.34680, in 0.003s
[8/100] 1 tree, 4 leaves, max depth = 2, train loss: 1358131.78461, val loss: 1293387.31812, in 0.003s
[9/100] 1 tree, 4 leaves, max depth = 2, train loss: 1235304.05933, val loss: 1182057.31762, in 0.003s
[10/100] 1 tree, 4 leaves, max depth = 2, train loss: 1142471.60535, val loss: 1097967.46039, in 0.003s
[11/100] 1 tree, 4 leaves, max depth = 2, train loss: 1075416.19106, val loss: 1036877.91931, in 0.003s
[12/100] 1 tree, 4 leaves, max depth = 2, train loss: 1025603.93283, val loss: 989495.94151, in 0.003s
[13/100] 1 tree, 4 leaves, max depth = 2, train loss: 975532.47138, val loss: 944176.60544, in 0.003s
[14/100] 1 tree, 4 leaves, max depth = 2, train loss: 940513.58186, val loss: 914058.76771, in 0.003s
[15/100] 1 tree, 4 leaves, max depth = 2, train loss: 906319.78285, val loss: 883578.42595, in 0.003s
[16/100] 1 tree, 4 leaves, max depth = 2, train loss: 879510.25263, val loss: 858174.30155, in 0.003s
[17/100] 1 tree, 4 leaves, max depth = 2, train loss: 857878.44174, val loss: 837587.73770, in 0.003s
[18/100] 1 tree, 4 leaves, max depth = 2, train loss: 834603.52194, val loss: 818939.97339, in 0.004s
[19/100] 1 tree, 4 leaves, max depth = 2, train loss: 816933.42168, val loss: 800666.68782, in 0.003s
[20/100] 1 tree, 4 leaves, max depth = 2, train loss: 797902.75850, val loss: 783036.38428, in 0.003s
[21/100] 1 tree, 4 leaves, max depth = 2, train loss: 775624.67458, val loss: 761301.99283, in 0.003s
[22/100] 1 tree, 4 leaves, max depth = 2, train loss: 761483.35056, val loss: 748708.97524, in 0.003s
[23/100] 1 tree, 4 leaves, max depth = 2, train loss: 749783.06979, val loss: 736251.93195, in 0.003s
[24/100] 1 tree, 4 leaves, max depth = 2, train loss: 734370.02300, val loss: 720683.89226, in 0.003s
[25/100] 1 tree, 4 leaves, max depth = 2, train loss: 723452.80019, val loss: 710140.00640, in 0.003s
[26/100] 1 tree, 4 leaves, max depth = 2, train loss: 705011.11108, val loss: 691458.07841, in 0.003s
[27/100] 1 tree, 4 leaves, max depth = 2, train loss: 696645.75513, val loss: 682565.30129, in 0.003s
[28/100] 1 tree, 4 leaves, max depth = 2, train loss: 685513.41927, val loss: 671990.69700, in 0.003s
[29/100] 1 tree, 4 leaves, max depth = 2, train loss: 677271.93581, val loss: 664898.93863, in 0.003s
[30/100] 1 tree, 4 leaves, max depth = 2, train loss: 666889.34975, val loss: 655544.46951, in 0.003s
[31/100] 1 tree, 4 leaves, max depth = 2, train loss: 658158.77020, val loss: 647127.15619, in 0.003s
[32/100] 1 tree, 4 leaves, max depth = 2, train loss: 651158.64597, val loss: 640152.73428, in 0.003s
[33/100] 1 tree, 4 leaves, max depth = 2, train loss: 638339.14928, val loss: 629611.24188, in 0.003s
[34/100] 1 tree, 4 leaves, max depth = 2, train loss: 627108.21087, val loss: 618121.67545, in 0.004s
[35/100] 1 tree, 4 leaves, max depth = 2, train loss: 620788.27075, val loss: 611574.23945, in 0.003s
[36/100] 1 tree, 4 leaves, max depth = 2, train loss: 614689.11287, val loss: 606236.95328, in 0.002s
[37/100] 1 tree, 4 leaves, max depth = 2, train loss: 608209.85262, val loss: 600764.35645, in 0.003s
[38/100] 1 tree, 4 leaves, max depth = 2, train loss: 602890.58333, val loss: 595613.76510, in 0.003s
[39/100] 1 tree, 4 leaves, max depth = 2, train loss: 597931.08397, val loss: 590286.51836, in 0.003s
[40/100] 1 tree, 4 leaves, max depth = 2, train loss: 588832.19648, val loss: 580709.54683, in 0.010s
[41/100] 1 tree, 4 leaves, max depth = 2, train loss: 574673.41935, val loss: 570411.58096, in 0.003s
[42/100] 1 tree, 4 leaves, max depth = 2, train loss: 570456.03863, val loss: 565939.10047, in 0.003s
[43/100] 1 tree, 4 leaves, max depth = 2, train loss: 565986.33526, val loss: 561892.34592, in 0.003s
[44/100] 1 tree, 4 leaves, max depth = 2, train loss: 560354.06322, val loss: 557936.10531, in 0.003s
[45/100] 1 tree, 4 leaves, max depth = 2, train loss: 555792.09845, val loss: 553304.27006, in 0.004s
[46/100] 1 tree, 4 leaves, max depth = 2, train loss: 552371.03077, val loss: 550465.35420, in 0.003s
[47/100] 1 tree, 4 leaves, max depth = 2, train loss: 546261.83408, val loss: 543971.15155, in 0.002s
[48/100] 1 tree, 4 leaves, max depth = 2, train loss: 536681.89633, val loss: 536626.40707, in 0.003s
[49/100] 1 tree, 4 leaves, max depth = 2, train loss: 533110.70745, val loss: 532879.43536, in 0.003s
[50/100] 1 tree, 4 leaves, max depth = 2, train loss: 529446.26691, val loss: 529387.67653, in 0.003s
[51/100] 1 tree, 4 leaves, max depth = 2, train loss: 526649.55778, val loss: 531196.45344, in 0.003s
[52/100] 1 tree, 4 leaves, max depth = 2, train loss: 523816.28824, val loss: 527571.44835, in 0.002s
[53/100] 1 tree, 4 leaves, max depth = 2, train loss: 519183.49273, val loss: 523630.27692, in 0.002s
[54/100] 1 tree, 4 leaves, max depth = 2, train loss: 512506.37763, val loss: 519310.41845, in 0.003s
[55/100] 1 tree, 4 leaves, max depth = 2, train loss: 509187.57000, val loss: 516025.68921, in 0.003s
[56/100] 1 tree, 4 leaves, max depth = 2, train loss: 506161.64898, val loss: 512688.02019, in 0.002s
[57/100] 1 tree, 4 leaves, max depth = 2, train loss: 504342.99517, val loss: 510109.56627, in 0.003s
[58/100] 1 tree, 4 leaves, max depth = 2, train loss: 502106.41142, val loss: 507586.06869, in 0.002s
[59/100] 1 tree, 4 leaves, max depth = 2, train loss: 498315.45974, val loss: 504020.23658, in 0.002s
[60/100] 1 tree, 4 leaves, max depth = 2, train loss: 493107.81021, val loss: 498511.89919, in 0.003s
[61/100] 1 tree, 4 leaves, max depth = 2, train loss: 490724.07750, val loss: 496195.54271, in 0.003s
[62/100] 1 tree, 4 leaves, max depth = 2, train loss: 487949.26183, val loss: 492996.25391, in 0.003s
[63/100] 1 tree, 4 leaves, max depth = 2, train loss: 481985.61604, val loss: 487931.98856, in 0.003s
[64/100] 1 tree, 4 leaves, max depth = 2, train loss: 479110.38635, val loss: 485711.54786, in 0.002s
[65/100] 1 tree, 4 leaves, max depth = 2, train loss: 477300.54160, val loss: 484028.17711, in 0.003s
[66/100] 1 tree, 4 leaves, max depth = 2, train loss: 475283.27685, val loss: 481788.93676, in 0.004s
[67/100] 1 tree, 4 leaves, max depth = 2, train loss: 470871.37602, val loss: 479369.31066, in 0.003s
[68/100] 1 tree, 4 leaves, max depth = 2, train loss: 468569.88290, val loss: 477489.45048, in 0.003s
[69/100] 1 tree, 4 leaves, max depth = 2, train loss: 464404.78597, val loss: 473604.70343, in 0.003s
[70/100] 1 tree, 4 leaves, max depth = 2, train loss: 463088.66683, val loss: 471356.48763, in 0.003s
[71/100] 1 tree, 4 leaves, max depth = 2, train loss: 461443.36112, val loss: 470377.59377, in 0.003s
[72/100] 1 tree, 4 leaves, max depth = 2, train loss: 459860.87212, val loss: 468859.06593, in 0.004s
[73/100] 1 tree, 4 leaves, max depth = 2, train loss: 457742.00222, val loss: 466667.00793, in 0.003s
[74/100] 1 tree, 4 leaves, max depth = 2, train loss: 454244.34543, val loss: 462880.65991, in 0.003s
[75/100] 1 tree, 4 leaves, max depth = 2, train loss: 452800.84646, val loss: 461380.57627, in 0.002s
[76/100] 1 tree, 4 leaves, max depth = 2, train loss: 450473.43215, val loss: 459330.42668, in 0.003s
[77/100] 1 tree, 4 leaves, max depth = 2, train loss: 447556.37487, val loss: 456610.01474, in 0.004s
[78/100] 1 tree, 4 leaves, max depth = 2, train loss: 444049.80549, val loss: 453077.55916, in 0.003s
[79/100] 1 tree, 4 leaves, max depth = 2, train loss: 442275.86045, val loss: 451530.92867, in 0.003s

[80/100] 1 tree, 4 leaves, max depth = 2, train loss: 440900.97220, val loss: 450247.42918, in 0.002s
[81/100] 1 tree, 4 leaves, max depth = 2, train loss: 437929.76077, val loss: 448569.88414, in 0.003s
[82/100] 1 tree, 4 leaves, max depth = 2, train loss: 435038.17898, val loss: 445526.90613, in 0.004s
[83/100] 1 tree, 4 leaves, max depth = 2, train loss: 433716.93482, val loss: 444313.65783, in 0.004s
[84/100] 1 tree, 4 leaves, max depth = 2, train loss: 431969.56531, val loss: 443452.00083, in 0.003s
[85/100] 1 tree, 4 leaves, max depth = 2, train loss: 430372.32056, val loss: 442032.23098, in 0.003s
[86/100] 1 tree, 4 leaves, max depth = 2, train loss: 429389.88755, val loss: 441088.32850, in 0.002s
[87/100] 1 tree, 4 leaves, max depth = 2, train loss: 428488.27793, val loss: 440303.58197, in 0.003s
[88/100] 1 tree, 4 leaves, max depth = 2, train loss: 426165.74292, val loss: 437687.05046, in 0.003s
[89/100] 1 tree, 4 leaves, max depth = 2, train loss: 425400.99047, val loss: 437017.99859, in 0.002s
[90/100] 1 tree, 4 leaves, max depth = 2, train loss: 423474.82199, val loss: 435038.03746, in 0.003s
[91/100] 1 tree, 4 leaves, max depth = 2, train loss: 422318.40817, val loss: 434019.34996, in 0.002s
[92/100] 1 tree, 4 leaves, max depth = 2, train loss: 419495.24562, val loss: 431348.98006, in 0.003s
[93/100] 1 tree, 4 leaves, max depth = 2, train loss: 418713.18248, val loss: 428911.32695, in 0.003s
[94/100] 1 tree, 4 leaves, max depth = 2, train loss: 413796.02706, val loss: 424802.42580, in 0.003s
[95/100] 1 tree, 4 leaves, max depth = 2, train loss: 412325.57002, val loss: 424096.14533, in 0.003s
[96/100] 1 tree, 4 leaves, max depth = 2, train loss: 411100.28356, val loss: 423018.54302, in 0.003s
[97/100] 1 tree, 4 leaves, max depth = 2, train loss: 410070.47190, val loss: 422348.39784, in 0.003s
[98/100] 1 tree, 4 leaves, max depth = 2, train loss: 408350.91766, val loss: 420513.67950, in 0.004s
[99/100] 1 tree, 4 leaves, max depth = 2, train loss: 407807.54707, val loss: 420051.53405, in 0.003s
[100/100] 1 tree, 4 leaves, max depth = 2, train loss: 406385.80338, val loss: 418747.26338, in 0.003s
Fit 100 trees in 0.373 s, (400 total leaves)
Time spent computing histograms: 0.103s
Time spent finding best splits:  0.010s
Time spent applying splits:      0.024s
Time spent predicting:           0.008s
Model: HistGradientBoostingRegressor(learning_rate=0.18, max_depth=2,
                              max_leaf_nodes=32, n_iter_no_change=8,
                              random_state=42, verbose=1)

In [77]:
# Model predictions

predictions = model.predict(X_test)

print(type(predictions))

<class 'numpy.ndarray'>

In [78]:
# Visual check

check = pd.DataFrame({'Ground truth':y_test, 'Predictions':predictions, 'Diff':y_test-predictions})
check

       Ground truth  Predictions         Diff
17775           660   691.805513   -31.805513
13506          1793  1756.076062    36.923938
4325           1913  1897.912037    15.087963
37870          7117  8529.174077 -1412.174077
21321          2177  1780.147323   396.852677
...             ...          ...          ...
3781            829   991.098216  -162.098216
26959          7279  7649.196802  -370.196802
15529          4914  4486.788543   427.211457
36333           476   615.158450  -139.158450
31606          3276  3747.774495  -471.774495

[8091 rows x 3 columns]

In [79]:
# RMSE

tricky_error = round(mean_squared_error(y_test, predictions)**0.5, 5)
tricky_error

913.25165

In [ ]:
check.reset_index(inplace=False)
check
check.plot( y=['Ground truth', 'Predictions'], kind='line', figsize=(20, 10),linewidth=1.5, linestyle='-');
check.plot(y=['Diff'], kind='line')

In [ ]:
# Save model using pickle

filename = './data/model6c.sav'
pickle.dump(model, open(filename, 'wb'))
print('Your model has been saved with  pickle!!!')

#MODEL 3=> SVR RMSE 4350.74274
#MODEL 4=>GradientBoostingRegressor RMSE 859.89564
#MODEL 5=> DecisionTreeClassifier RMSE 1326.36031, este problema es de regresiÃ³n, no de clasificaciÃ³n: no vale para este caso.
#MODEL 6=>HistGradientBoostingRegressor RMSE 591.21308--> va ganando
#MODEL 7-> DtABOOST REGRESOR. RMSE= 1553.94206
#model 8--> extra trees regresor RMSE 610.6722